version: '3'
services:
  website-frontend:
    image: "jzlotek/personal-website"
    restart: unless-stopped
    container_name: "website-frontend"
    ports:
      - 5000:5000
  watchtower:
    image: "containrrr/watchtower"
    restart: unless-stopped
    container_name: "watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock